services:
  ambassador_backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: 'npm run start'
    ports:
      - 8003:8000
    volumes:
      - '.:/app'
    depends_on:
      - ambassador_db
      - redis
    networks:
      - ambassador
      - users
  
  ambassador_consumer:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: 'npm run consume'
    depends_on:
      - ambassador_db
    networks:
      - ambassador

  ambassador_db:
    image: postgres:15.3
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./.pgdata:/var/lib/postgresql/data # Volume for persisting PostgreSQL data
    ports:
      - 54324:5432
    networks:
      - ambassador
      
  redis: # never rename this to anything, use redis
    image: redis
    ports:
      - 6379:6379
    networks:
      - ambassador

networks:
  ambassador:
  users:
    external: true