services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - '.:/app'
    depends_on:
      - db
    networks:
      - ambassador_network
      
  db:
    image: postgres:15.3
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./.pgdata:/var/lib/postgresql/data # Volume for persisting PostgreSQL data
    ports:
      - 54323:5432
    networks:
      - ambassador_network
      
  redis: # never rename this to anything, use redis
    image: redis
    ports:
      - 6379:6379
    networks:
      - ambassador_network

networks:
  ambassador_network: