services:
  admin_backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: 'npm start'
    ports:
      - 8002:8000
    volumes:
      - '.:/app'
    depends_on:
      - admin_db
    networks:
      - admin
      - users

  admin_consumer:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: 'npm run consume'
    depends_on:
      - admin_db
    networks:
      - admin

  admin_db:
    image: postgres:15.3
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./.pgdata:/var/lib/postgresql/data # Volume for persisting PostgreSQL data
    ports:
      - 54322:5432
    networks:
      - admin

networks:
  admin:
  users:
    external: true