services:
  users_backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: users_ms
    volumes:
      - '.:/app'
    depends_on:
      - users_db
    networks:
      - users

  users_db:
    image: postgres:15.3
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./.pgdata:/var/lib/postgresql/data # Volume for persisting PostgreSQL data
    ports:
      - 54321:5432
    networks:
      - users

networks:
  users:
    name: users
